# ── NOTES.md ─────────────────────────────────────────────────────────────────
# The whole function writes MARKDOWN: single-quoted printf formats full of
# backticks (code spans) and literal $VARs the reader is meant to see. Not
# expanding them is the point, so SC2016 is silenced for the block rather than
# line by line.
# shellcheck disable=SC2016
write_notes() {
  # $f is the spelling; only the redirect resolves it.
  local f=$EMIT_DIR/NOTES.md box port bs hs data pcache note
  {
    printf '# droste-halo setup notes\n\n'
    printf 'Generated by droste-setup.sh on %s. Re-run droste-setup.sh any time —\n' \
      "$(date +%F)"
    printf 'existing boxes are detected and never clobbered.\n\n'
    printf '## One container, two doors\n\n'
    printf 'Each box is ONE podman container, `droste-<box>-halo`, created by\n'
    printf '`distrobox assemble` from its `<box>-halo.ini`:\n\n'
    printf -- '- **Interactive door** — `distrobox enter droste-<box>-halo`.\n'
    printf '  A shell in your own $HOME, with the box%s toolchain.\n' "'s"
    printf -- '- **Server door** — `podman start droste-<box>-halo`. Starting the\n'
    printf '  container replays its init line, which reads `<box>.cfg` from the\n'
    printf '  box%s data dir and launches the service on the port recorded there.\n' "'s"
    printf '\nEntering a stopped box therefore starts it — and, if its\n'
    printf '`DROSTE_<APP>_STARTUP_ENABLED` is `yes`, its service with it. Both doors\n'
    printf 'are the SAME environment: a `pip install` you do interactively is what\n'
    printf 'the served process runs.\n'
    printf '\n## Your installation\n\n'
    printf '| Box | Start w Box | Start w Host | Port | Data dir | Cache dir |\n'
    printf '|---|---|---|---|---|---|\n'
    for box in "${SELECTED[@]}"; do
      port=$(box_port_disp "$box")
      bs=$(yn_word "$(box_boxsv "$box")")
      hs=$(yn_word "$(box_hstsv "$box")")
      data="${PATHS["$box:data"]:-${EXD_PATH["$box:data"]:-?}}"
      # A box carried over from an older layout has no cache dir of its own to
      # report (nothing bound one); it says so rather than naming a path the
      # ini does not carry.
      pcache="${PATHS["$box:pcache"]:-${EXD_PATH["$box:pcache"]:-?}}"
      printf '| %s | %s | %s | %s | %s | %s |\n' \
        "$box" "$bs" "$hs" "$port" "$data" "$pcache"
    done
    printf '\nShared HF cache: `%s` — bound into every box; the SINGLE model\n' \
      "$HF_CACHE"
    printf 'store (a model one box downloads is available to all the others).\n'
    if [[ -n $MODELS_DIR ]]; then
      printf 'Local model collection: `%s` — bound read-only at `/opt/models`\n' \
        "$MODELS_DIR"
      printf 'in every box that supports it (comfyui/llama/vllm/ds4). The dir was\n'
      printf 'confirmed-or-created at setup time, so the bind is safe and already\n'
      printf 'present in the single `volume=` value of each ini.\n'
    else
      printf 'Local model collection: not configured (/opt/models unbound).\n'
    fi
    printf 'Shared compute cache: %s — bound at /opt/caches in every\n' \
      "\`$COMPUTE_CACHE\`"
    printf 'box (MIOpen/Triton/torch/vLLM kernels; safe to share — content is\n'
    printf 'keyed by version/arch). ONE caveat: avoid heavy simultaneous\n'
    printf 'first-run MIOpen tuning in two boxes at once; everything else\n'
    printf 'is conflict-free.\n'
    # The Q4 write-up: three host roots, told as "what may be deleted", which
    # is the only distinction between them a user has to remember. The paths
    # themselves are in the table above (they are per box, and may have been
    # typed one by one), so this names the ROLES.
    printf '\n## Three places your files live\n\n'
    printf 'Every box reads three host directories, and what separates them is\n'
    printf 'what may be thrown away:\n\n'
    printf -- '- **Data dir** (`data/<box>` by default) — PERSISTENT. Your work and\n'
    printf '  everything you authored: the seeded config you edited, the model\n'
    printf '  tree, ComfyUI%s `user/` and custom nodes, ds4%s saved sessions, the\n' \
      "'s" "'s"
    printf '  finetuning workspace, your `<box>.cfg`. droste-setup.sh deletes\n'
    printf '  nothing here unasked: the one way it ever does is the "remove data\n'
    printf '  at new path" answer, when a move you accepted lands on a directory\n'
    printf '  that already has something in it — and that question names the\n'
    printf '  directory first.\n'
    printf -- '- **Cache dir** (`caches/<box>` by default) — PROGRAM CACHES, and\n'
    printf '  nothing else: the Python environment overlay and its work dir,\n'
    printf '  scratch temp, llama%s saved-prompt slots, ds4%s KV disk, the seeded\n' \
      "'s" "'s"
    printf '  `extra_model_paths.yaml`, the server state dir. Nothing in here is\n'
    printf '  authored and nothing is irreplaceable — droste-setup.sh offers to\n'
    printf '  EMPTY it when it finds leftovers from an older generation, and the\n'
    printf '  box rebuilds what it needs at the next start.\n'
    printf -- '- **Compute caches** (`%s`) — the compiled GPU\n' "$COMPUTE_CACHE"
    printf '  kernels, SHARED by every box because their content is keyed by\n'
    printf '  version and architecture. compute-caches is safe to delete anytime;\n'
    printf '  kernels rebuild on next start. The installer never touches it.\n'
    printf '\n## Day-to-day commands\n\n'
    printf '    podman start <name>        # start the box (+ its server)\n'
    printf '    podman stop <name>         # stop it\n'
    printf '    podman logs -f <name>      # follow its log\n'
    printf '    podman ps                  # STATUS shows the healthcheck\n'
    printf '    distrobox enter <name>     # interactive shell in the box\n\n'
    printf 'Names:\n'
    for box in "${SELECTED[@]}"; do
      printf '  %s\n' "$(box_ctr "$box")"
    done
    printf '\n## Starting and stopping the server\n\n'
    printf 'There are TWO settings, and the difference is how long they last.\n\n'
    printf '**Right now** — run these INSIDE the box (`distrobox enter <name>`):\n\n'
    printf '    server_status     # what the box wants, and what is really true\n'
    printf '    server_start      # start this box%s server now\n' "'s"
    printf '    server_stop       # stop it — until the box next starts\n'
    printf '    server_restart    # stop, then start\n\n'
    printf 'A `server_stop` is deliberately TEMPORARY: the server comes back the\n'
    printf 'next time the box starts, so you can never leave a box quietly dead\n'
    printf 'and forget why. These verbs act on the SERVER; to restart the whole\n'
    printf 'container use `podman restart <name>`.\n\n'
    printf '**Permanently** — two settings in the box%s OWN config file, read at\n' "'s"
    printf 'EVERY box start. That file is seeded from the image the first time the\n'
    printf 'box starts and is YOURS from then on; it also documents every other\n'
    printf 'setting the application takes. STARTUP_ENABLED takes `{yes, no}` (no =\n'
    printf 'interactive only, nothing is launched); PORT is the port the server\n'
    printf 'BINDS — these boxes share the host network, so nothing is remapped.\n'
    printf 'Yours, from the answers you gave this run:\n\n'
    for box in "${SELECTED[@]}"; do
      data="${PATHS["$box:data"]:-${EXD_PATH["$box:data"]:-<data-dir>}}"
      printf '    %s/%s\n' "$data" "${BOX_CFG[$box]}"
      printf '      DROSTE_%s_STARTUP_ENABLED=%s\n' \
        "${BOX_APP[$box]}" "$(yn_word "$(box_boxsv "$box")")"
      printf '      DROSTE_%s_PORT=%s\n' \
        "${BOX_APP[$box]}" "$(box_port_disp "$box")"
    done
    printf '\nEdit and `podman restart <name>` — no recreate needed, and the file\n'
    printf 'survives image updates and box recreation. droste-setup.sh MERGES those\n'
    printf 'two lines, one line at a time, for every box it CREATES: everything\n'
    printf 'else in the file comes out exactly as you wrote it, comments included.\n'
    printf 'Boxes you asked to KEEP are not touched at all, and a run that stopped\n'
    printf 'short of creating a box has not recorded them anywhere but the box%s\n' "'s"
    printf 'ini — create the box and they land in the file above.\n\n'
    printf 'That is also why a newly created box is started once before your\n'
    printf 'answers are recorded: the box has to seed its own config file before\n'
    printf 'there is anything to record them in. The installer never writes that\n'
    printf 'file itself — a file already sitting there would stop the box seeding\n'
    printf 'it, and you would lose every other setting in it.\n'
    printf '\n## Supervision (podman healthcheck)\n\n'
    printf 'Each box is created with a healthcheck that probes its service from\n'
    printf 'inside (`--health-on-failure=restart`), so a wedged or crashed server\n'
    printf 'is brought back. A box that is not meant to be serving right now\n'
    printf 'always reports healthy — the probe knows the difference.\n\n'
    printf 'The server is relaunched ON ITS OWN first: only if that fails does\n'
    printf 'the whole container restart, so a crashed server no longer closes\n'
    printf 'the shells of anyone working in the box. If you stopped the server\n'
    printf 'yourself with `server_stop`, nothing restarts anything — the box\n'
    printf 'knows you meant it.\n\n'
    printf 'The probe checks TWO things: that the service THIS box started is\n'
    printf 'still running, and that it answers. Both are needed because the boxes\n'
    printf 'share the host network: if the port in `<box>.cfg` is already taken\n'
    printf 'when the box starts, the box does NOT start a second listener (it\n'
    printf 'says so in `<data dir>/.droste-serve.log`) and reports UNHEALTHY —\n'
    printf 'the stranger on that port is not your server. Give the box its own\n'
    printf 'port or free that one; each restart retries.\n\n'
    printf 'The START PERIOD is generous on purpose (these services answer\n'
    printf 'nothing while they load multi-GB weights; llama even answers 503):\n\n'
    for box in "${SELECTED[@]}"; do
      printf '    %-12s %s\n' "$box" "${BOX_HEALTH_START[$box]}"
    done
    printf '\nInspect it with `podman inspect --format "{{json .State.Health}}"`.\n'
    printf '\n## Stopping: what actually happens\n\n'
    printf 'The box%s pid 1 is distrobox-init, which does NOT forward SIGTERM to\n' "'s"
    printf 'the served process, so `podman stop` on its own cannot ask the server\n'
    printf 'to exit — it kills it at the `--stop-timeout %s` ceiling.\n' \
      "$STOP_TIMEOUT"
    printf 'The systemd unit above therefore runs `server_stop` INSIDE the box\n'
    printf 'first, which does ask it, and only then stops the container. If you\n'
    printf 'stop a box by hand and want the same courtesy, run `server_stop` in\n'
    printf 'the box before `podman stop`. Nothing in these images buffers state\n'
    printf 'that a clean shutdown would flush, so this is politeness rather than\n'
    printf 'protection.\n'
    printf '\n## Per-box quickstart\n'
    for box in "${SELECTED[@]}"; do
      data="${PATHS["$box:data"]:-${EXD_PATH["$box:data"]:-<data-dir>}}"
      port=$(box_port_disp "$box")
      printf '\n### %s — %s\n\n' "$box" "${BOX_PITCH[$box]}"
      case "$box" in
        comfyui)
          printf -- '- Web UI: http://localhost:%s.\n' "$port"
          printf -- '- Models are scanned from the shared HF cache (+ /opt/models)\n'
          printf '  at every start; new downloads appear in the pickers.\n'
          printf -- '- Your work dirs: input `%s`, output `%s`.\n' \
            "${PATHS["$box:input"]:-${EXD_PATH["$box:input"]:-?}}" \
            "${PATHS["$box:output"]:-${EXD_PATH["$box:output"]:-?}}"
          ;;
        llama)
          printf -- '- BEFORE first use: edit `%s/llama.cfg` and set\n' "$data"
          printf '  `LLAMA_ARG_MODEL` (a GGUF path, or use `-hf org/repo` via\n'
          printf '  `DROSTE_LLAMA_EXTRA_ARGS`). The file is seeded at first start.\n'
          printf -- '- API: http://localhost:%s (llama-server).\n' "$port"
          ;;
        vllm)
          printf -- '- BEFORE first use: edit `%s/vllm_config.yaml` and set\n' "$data"
          printf '  `model:` (HF repo id or /opt/models path). Seeded at first start.\n'
          printf '  REQUIRED: left unset, vLLM exits with `No model specified!`\n'
          printf '  and the server never starts.\n'
          printf -- '- OpenAI-compatible API: http://localhost:%s/v1.\n' "$port"
          ;;
        ds4)
          printf -- '- BEFORE first use: edit `%s/ds4.cfg` and set\n' "$data"
          printf '  `DROSTE_DS4_MODEL` (GGUF path). Seeded at first start.\n'
          printf -- '- API: http://localhost:%s (ds4-server).\n' "$port"
          ;;
        finetuning)
          printf -- '- JupyterLab: http://localhost:%s — get the login token with\n' \
            "$port"
          # NOT `podman logs`: droste-serve.sh redirects the server's stdout AND
          # stderr into $DROSTE_SERVE_LOG, so the container log never carries the
          # token line. finetuning.cfg documents this exact command; keep them
          # the same, and if one moves, move both.
          printf "    podman exec %s grep -o 'token=[0-9a-f]*' /opt/data/.droste-serve.log | tail -1\n" \
            "$(box_ctr finetuning)"
          printf -- '- Notebooks + trained adapters live in your workspace:\n'
          printf '  `%s`.\n' \
            "${PATHS["$box:workspace"]:-${EXD_PATH["$box:workspace"]:-?}}"
          ;;
      esac
    done
    printf '\n## Recreate one-liners\n\n'
    for box in "${SELECTED[@]}"; do
      # The test resolves; the line printed does NOT — it is a command the
      # reader pastes into a shell, which expands a ~ itself.
      if [[ -f $(fs_path "$(ini_file "$box")") ]]; then
        printf '    distrobox assemble create --file %s\n' "$(ini_file "$box")"
      fi
    done
    printf '\nRecreating replaces the container; your data dir, your cache dir,\n'
    printf 'your `<box>.cfg` and the in-box overlays under them are untouched — that\n'
    printf 'is what makes in-box installs survive a recreate (pip packages ride\n'
    printf 'the environment overlay in the cache dir, custom nodes their own\n'
    printf 'overlay in the data dir).\n'
    # The ini is the one generated file a user is invited to edit, and the
    # spelling record is the one line in it that looks like machinery. Explain
    # both here rather than leaving the reader to guess what may be touched.
    printf '\n## Editing a box%s ini by hand\n\n' "'s"
    printf 'Every bind a box has lives in the ONE `volume=` value of its ini:\n'
    printf '`distrobox assemble` reads only the LAST `volume=` key, so a second\n'
    printf 'line would silently drop the first. Its sources are written out in\n'
    printf 'full because that is what podman binds — a source that does not begin\n'
    printf 'with `/` or `./` is read as the NAME of a named volume, so a `~`\n'
    printf 'there would quietly stop being a bind at all.\n\n'
    printf 'Underneath it sits a record line, shaped like this:\n\n'
    printf '    # droste-setup: spelled="~/droste/data/<box>:/opt/data ..."\n\n'
    printf 'That is the same list of binds in the spelling you typed. It is what\n'
    printf 'lets droste-setup.sh show you your own paths on the next run rather\n'
    printf 'than a reconstruction of them, and it is rewritten from your answers\n'
    printf 'every time, so there is nothing to maintain there by hand. Change a\n'
    printf 'bind in `volume=` and it takes effect: `volume=` WINS when the two\n'
    printf 'disagree, and the record simply stops naming that directory.\n'
    printf '\n## Start at host boot\n\n'
    printf 'Boxes you asked to start at host boot get a systemd USER unit:\n\n'
    printf '    systemctl --user status droste-<box>      # is it enabled/active\n'
    printf '    systemctl --user disable droste-<box>     # stop starting at boot\n\n'
    printf 'The unit is a oneshot doing `podman start droste-<box>-halo`. Rootless\n'
    printf 'user services (and podman%s healthcheck timers) need LINGERING, or the\n' "'s"
    printf 'user manager exits at logout and takes both with it:\n\n'
    printf '    loginctl enable-linger %s\n\n' "${USER:-$(id -un)}"
    printf 'droste-setup.sh enables it for you when a box asks for host boot (no\n'
    printf 'sudo needed in a local session); prefix with `sudo` if it refused.\n'
    printf '\n## Shared model store\n\n'
    printf 'Every box binds `%s`. Download once, use everywhere:\n\n' "$HF_CACHE"
    printf '    hf download <org>/<repo>       # or: huggingface-cli download\n\n'
    printf 'ComfyUI re-scans the cache at each start (symlink model tree).\n'
    printf '\n## Installer choices (record)\n\n'
    printf -- '- Date: %s; emit dir: `%s`; runtime: %s%s.\n' \
      "$(date +%F)" "$EMIT_DIR" "${RUNTIME:-none}" \
      "$([[ $ROOTLESS -eq 1 ]] && echo ' (rootless)')"
    for box in "${CONFIGURE[@]}"; do
      note=""
      case "${CFG_MODE[$box]:-}" in
        fuse) note="fs=${CFG_FS[$box]} → DROSTE_OVERLAY_MODE=fuse + /dev/fuse" ;;
        copy) note="fs=${CFG_FS[$box]} → DROSTE_OVERLAY_MODE=copy" ;;
        ignore) note="fs=${CFG_FS[$box]} → IGNORED (box will fail on start!)" ;;
        *) note="fs=${CFG_FS[$box]:-?} (kernel overlayfs OK)" ;;
      esac
      printf -- '- %s: port=%s, box-start=%s, host-boot=%s, data=`%s`, cache=`%s`, %s.%s\n' \
        "$box" "${CFG_PORT[$box]}" "$(yn_word "${CFG_BOXSV[$box]:-}")" \
        "$(yn_word "${CFG_HSTSV[$box]:-}")" "${PATHS["$box:data"]}" \
        "${PATHS["$box:pcache"]}" "$note" \
        "$(printf ' Settings: %s.' "${BOX_CFG[$box]}")$([[ -n ${BOX_CFG_EXTRA[$box]} ]] \
           && printf ' Also seeded: %s.' "${BOX_CFG_EXTRA[$box]}")"
    done
    printf '\nEscape hatch: `-e ALLOW_EPHEMERAL=1` downgrades missing-critical-\n'
    printf 'bind errors to warnings (NOT recommended — data will not persist).\n'
    printf '\n## Health check\n\n'
    printf 'On the GPU host, the repo'\''s `scaffolding/check-rocm.sh` validates\n'
    printf 'GPU access + per-box smoke across all images (see its --help).\n'
  } > "$(fs_path "$f")"
  # Jei's "---" is deliberate: a plain rule that says "that part is done",
  # closing the run's chattiest phase before the final report opens below.
  printf '\n%s---%s\n%sWrote %s.%s\n' \
    "$C_TEXT" "$RESET" "$C_FILE" "$f" "$RESET"
  return 0
}

# ── Status dashboard ─────────────────────────────────────────────────────────
box_port_disp() {
  local box=$1
  printf '%s' "${CFG_PORT[$box]:-${EXD_PORT[$box]:--}}"
}
# The two toggles, from this run's answers when there are any (configured or
# hydrated-keep boxes both have them) and from detection otherwise.
box_boxsv() {
  local box=$1
  if [[ -n "${CFG_PORT[$box]:-}" ]]; then printf '%s' "${CFG_BOXSV[$box]:-}"
  else printf '%s' "${EXD_BOXSV[$box]:-}"; fi
}
box_hstsv() {
  local box=$1
  if [[ -n "${CFG_PORT[$box]:-}" ]]; then printf '%s' "${CFG_HSTSV[$box]:-}"
  else printf '%s' "${EXD_HSTSV[$box]:-}"; fi
}

box_state() {  # box → ACTIVE|STOPPED|none|UNKNOWN
  local box=$1 state="" asked=0
  if [[ -n $RUNTIME ]]; then
    # Distinguish "asked, nothing there" from "could not ask": with no runtime, or
    # a query that errored, `none` would claim the box does not exist when the
    # truth is we have no way to tell. Only a successful query earns `none`.
    if state=$("$RUNTIME" ps -a --filter "name=^$(box_ctr "$box")\$" \
               --format '{{.State}}' 2>/dev/null | head -n1); then
      asked=1
    else
      state=""
    fi
  fi
  if [[ -z $state ]]; then
    if [[ -n "${SESSION_STATE[$box]:-}" ]]; then
      printf '%s' "${SESSION_STATE[$box]}"
    elif [[ -n "${EX_CTR[$box]:-}" ]]; then
      [[ ${EX_CTR[$box]} == running ]] && printf 'ACTIVE' || printf 'STOPPED'
    elif [[ $asked -eq 1 ]]; then
      printf 'none'
    else
      printf 'UNKNOWN'
    fi
  else
    [[ $state == running ]] && printf 'ACTIVE' || printf 'STOPPED'
  fi
}

# The table geometry:
#
#   Service     On  BoxSv  HstSv  Port  Important Notes
#   col 0       12  16     23     30    36
#
# The host key is HstSv in BOTH tails (Jei): at five characters it leaves the
# header field's two trailing spaces intact, so Port is never crowded — the
# six-character spelling ate one of them and read as a collision.
#
# A pull-and-write run drops the [On] cell (no container exists to report on).
# Its remaining columns are NOT the full layout minus a constant: the glyph
# columns of each layout are hand-tuned (see dash_table) because "centred under
# that header" is an eye judgement about double-width glyphs, not arithmetic.
# Only the Notes column is responsive; everything left of it is fixed so the
# columns line up between runs.
DASH_HOST_KEY="HstSv"

# ── Final-report blocks (shared by the pull-and-write tail and the full one) ─
# NOTHING here breaks a line by hand. The two hard breaks that used to live in
# this section (the Legend's host-boot key and the Shortcuts'
# "(stop to stop)") were transcription artifacts of a 60-column mockup, and they
# broke every terminal wide enough not to need it — the rows below all fit 80.
#
# dash_legend / dash_table — ONE code path each, for both tails. A
# pull-and-write run has no [On] cell (no container exists whose state it could
# report); that is a single optional segment in each, plus the layout's own
# column table. The CODE is shared; only the numbers differ.
dash_legend() {   # with-on(0|1)
  local on=$1 hl=$DASH_HOST_KEY onkey="" plain
  hdr "Legend"
  [[ $on -eq 1 ]] && onkey="[$C_SUBJ""On$C_TEXT] Running?  "
  # The keys ride ONE line when the drawn width can hold them, and stack onto a
  # second when it cannot — the layout Jei's phone-narrow mockup showed. The
  # measurement is of the PLAIN text: escape bytes occupy no columns.
  plain="Server  "
  [[ $on -eq 1 ]] && plain+="[On] Running?  "
  plain+="[BoxSv] Start with Box  [$hl] Start at Host Boot"
  if [[ ${#plain} -gt $(disp_width) ]]; then
    printf '%sServer  %s[%s%s%s] Start with Box%s\n' \
      "$C_TEXT" "$onkey" "$C_SUBJ" "BoxSv" "$C_TEXT" "$RESET"
    printf '%s        [%s%s%s] Start at Host Boot%s\n' \
      "$C_TEXT" "$C_SUBJ" "$hl" "$C_TEXT" "$RESET"
  else
    printf '%sServer  %s[%s%s%s] Start with Box  [%s%s%s] Start at Host Boot%s\n' \
      "$C_TEXT" "$onkey" "$C_SUBJ" "BoxSv" "$C_TEXT" "$C_SUBJ" "$hl" "$C_TEXT" "$RESET"
  fi
  # The values ride their own column table (below): tokens on one set of
  # columns, words on another.
  if [[ $on -eq 1 ]]; then
    dash_values "8 25 49" "13 31 55"
  else
    dash_values "10 34 60" "16 40 65"
  fi
  return 0
}

# The Legend's value row. ONE builder, a column table per layout — hand-tuned
# from Jei's drawings, because where a double-width glyph "looks right" under a
# word is an eye judgement. Padding to ABSOLUTE columns is what lets the same
# table serve both cell widths: the 3-column [Y] of --ascii eats one column of
# the gap that follows it, so every WORD still lands where the emoji put it.
dash_values() {   # "tok tok tok" "word word word"
  local -a vtok=() vlab=() vg=("$GS_YES" "$GS_NO" "$GS_NA")
  local -a vw=("yes" "no" "NA / unknown")
  local i n row dw=5
  read -r -a vtok <<<"$1"
  read -r -a vlab <<<"$2"
  row=$C_TEXT"Value"
  for (( i = 0; i < 3; i = i + 1 )); do
    n=$(( vtok[i] - dw )); [[ $n -lt 0 ]] && n=0
    row+=$(printf '%*s' "$n" "")$GB_L$C_GLYPH${vg[i]}$C_TEXT$GB_R
    dw=$(( vtok[i] + ${#GB_L} + W_STATE + ${#GB_R} ))
    n=$(( vlab[i] - dw )); [[ $n -lt 0 ]] && n=0
    row+=$(printf '%*s' "$n" "")${vw[i]}
    dw=$(( vlab[i] + ${#vw[i]} ))
  done
  printf '%s%s\n' "$row" "$RESET"
  return 0
}

dash_table() {   # with-on(0|1)
  local on=$1 hl=$DASH_HOST_KEY box st stg g note data row port budget head
  local -a gcol=() glyph=()
  local pcol ncol i n dw
  # HAND-TUNED GLYPH COLUMNS, one set per layout (Jei): a centering FORMULA
  # cannot be right here — the glyphs are double-width, the ASCII fallback is
  # not, and "looks centred under that header" is an eye judgement, not an
  # arithmetic one. These are the columns from his two drawings; the row builder
  # below pads to them absolutely, so both cell widths land in the same place.
  if [[ $on -eq 1 ]]; then
    # ...and per MODE for the middle column: [N] is a column wider than the
    # glyph, and at 18 it reads as crowding BoxSv's right edge.
    if [[ $ASCII -eq 1 ]]; then gcol=(12 17 24); else gcol=(12 18 24); fi
    pcol=30; ncol=36
  else
    gcol=(13 20);    pcol=26; ncol=32
  fi
  budget=$(( $(disp_width) - ncol ))
  # Underline the WORDS only — the column padding stays plain.
  head=$(pad_cell_u "Service" 7 12)
  [[ $on -eq 1 ]] && head+=$(pad_cell_u "On" 2 4)
  head+=$(pad_cell_u "BoxSv" 5 7)$(pad_cell_u "$hl" ${#hl} 7)$(pad_cell_u "Port" 4 6)
  printf '%s%s%s%s\n' "$head" "$C_HDR" "Important Notes" "$RESET"
  for box in "${SELECTED[@]}"; do
    glyph=()
    if [[ $on -eq 1 ]]; then
      st=$(box_state "$box")
      case "$st" in
        ACTIVE)  stg=$GS_YES ;;
        STOPPED) stg=$GS_NO ;;
        # `none` and UNKNOWN both render ⚫: "not there" and "could not ask" look
        # the same to the reader, and box_state keeps the distinction internally.
        *)       stg=$GS_NA ;;
      esac
      glyph+=("$stg")
    fi
    [[ -n "$(box_boxsv "$box")" ]] && g=$GS_YES || g=$GS_NO
    glyph+=("$g")
    [[ -n "$(box_hstsv "$box")" ]] && g=$GS_YES || g=$GS_NO
    glyph+=("$g")
    # Pad to each column ABSOLUTELY, tracking the display width written so far —
    # which is the only way one set of columns can serve a 2-column glyph and a
    # 3-column [Y] alike.
    row=$C_SVC$(pad_cell "$box" ${#box} 12)$C_GLYPH
    dw=12
    for (( i = 0; i < ${#gcol[@]}; i = i + 1 )); do
      n=$(( gcol[i] - dw )); [[ $n -lt 0 ]] && n=0
      row+=$(printf '%*s' "$n" "")${glyph[i]}
      dw=$(( gcol[i] + W_STATE ))
    done
    port=$(box_port_disp "$box")
    n=$(( pcol - dw )); [[ $n -lt 0 ]] && n=0
    row+=$(printf '%*s' "$n" "")$C_PORT$port
    dw=$(( pcol + ${#port} ))
    n=$(( ncol - dw )); [[ $n -lt 0 ]] && n=0
    row+=$(printf '%*s' "$n" "")
    data="${PATHS["$box:data"]:-${EXD_PATH["$box:data"]:-}}"
    note=${BOX_NOTE[$box]//@DATA@/${data:-~/droste/$box/data}}
    [[ -n $note ]] && row+=$C_TEXT$(fit_note "$note" "$budget")
    printf '%s%s\n' "$row" "$RESET"
  done
  return 0
}

# dash_shortcuts — the two doors. Label in body text; the command is decorated
# executable / verb / target, with the <box> you substitute picked out in blue.
# ONE container per box, so both doors take the SAME name.
dash_shortcuts() {
  hdr "Shortcuts"
  # "·<label:26><command>" plus the aside is 71 columns; when the drawn width
  # cannot hold that, the ASIDE (not the command — that is copy-paste payload)
  # moves under it, indented to the command column.
  if [[ 71 -gt $(disp_width) ]]; then
    printf '%s%s%-25s%s%s%s%s%s%s%s%s%s%s%s\n' "$C_TEXT" "$BULLET" \
      "Start/stop (background):" "$C_EXE" "podman " "$C_CMD" "start " \
      "$C_TGT" "droste-" "$C_PH" "<box>" "$C_TGT" "-halo" "$RESET"
    printf '%s%*s(%s%s%s%s%s)%s\n' "$C_TEXT" 26 "" \
      "$C_STOPW" "stop" "$C_STOPT" " to stop" "$C_TEXT" "$RESET"
  else
    printf '%s%s%-25s%s%s%s%s%s%s%s%s%s%s%s %s(%s%s%s%s%s)%s\n' "$C_TEXT" "$BULLET" \
      "Start/stop (background):" "$C_EXE" "podman " "$C_CMD" "start " \
      "$C_TGT" "droste-" "$C_PH" "<box>" "$C_TGT" "-halo" "$RESET" \
      "$C_TEXT" "$C_STOPW" "stop" "$C_STOPT" " to stop" "$C_TEXT" "$RESET"
  fi
  printf '%s%s%-25s%s%s%s%s%s%s%s%s%s%s%s\n' "$C_TEXT" "$BULLET" \
    "Enter (interactive):" "$C_EXE" "distrobox " "$C_CMD" "enter " \
    "$C_TGT" "droste-" "$C_PH" "<box>" "$C_TGT" "-halo" "$RESET"
  return 0
}

# The footnote every reporting tail ends on, above the pointer.
dash_footnote() {
  # The command at the end of the line is payload, so it wears the bold bright
  # blue of every other copy-me fragment rather than the footnote's italic.
  printf '%s%s%s%s%s%s\n' "$C_STAR" \
    "*ComfyUI models scanned at start; to add more run: " \
    "$RESET" "$C_PATHB" "hf download <shared cache>" "$RESET"
  return 0
}

# The one-liner that rebuilds a box from what this run wrote. TITLED BY THE
# CALLER: after a pull-and-write run the containers do not exist yet, so the
# command CREATES ("Create / Recreate"); in the full report it is the recovery
# move for containers that already exist ("Recreate"). Same block either way.
dash_recreate() {   # title
  printf '%s%s%s\n' "$C_SUB" "$1 (files in $EMIT_DIR)" "$RESET"
  printf '%s%s%-12s%s%s%s%s%s%s%s%s%s%s%s\n' "$C_TEXT" "$BULLET" "distrobox:" \
    "$C_EXE" "distrobox " "$C_CMD" "assemble create " \
    "$C_TGT" "--file " "$C_PH" "<box>" "$C_TGT" "-halo.ini" "$RESET"
  return 0
}

# The final pointer, the one line every run ends on.
dash_pointer() {
  printf '%s%s%s%s%s\n' "$C_ARROW" "$ARROW_G" "$C_TEXT" \
    "Definitions + full guide: $EMIT_DIR (ini, NOTES.md)" \
    "$RESET"
  say ""
  return 0
}

dashboard() {
  # WRITE-ONLY RUNS GET THE POINTER AND NOTHING ELSE (Jei, live test). Every
  # block below — Legend, the status table, Shortcuts, Recreate, the ComfyUI
  # footnote — reports on RUNTIME state: containers that exist, run, and serve.
  # Rung w created none of that, so all of it would be noise or, worse, a table
  # of dashes. The closing rule and "Wrote NOTES.md." are write_notes's, and
  # NOTES.md itself is still written in full — it is what the pointer points at.
  if [[ $RUNG == w ]]; then
    dash_pointer
    return 0
  fi
  # A PULL-AND-WRITE RUN gets an ADAPTED report (Jei's rev 2): images and
  # definitions exist, containers do not — so the [On] column goes (there is no
  # container whose state it could report) and the create one-liner comes BEFORE
  # the Shortcuts, because you must create a box before you can start it. The
  # BoxSv/HostSv glyphs are the settings this run just wrote.
  if [[ $RUNG == p ]]; then
    say ""
    dash_legend 0
    say ""
    dash_table 0
    say ""
    dash_recreate "Create / Recreate"
    say ""
    dash_shortcuts
    say ""
    dash_footnote
    dash_pointer
    return 0
  fi
  say ""
  dash_legend 1
  say ""
  dash_table 1
  say ""
  dash_shortcuts
  say ""
  # Here the containers DO exist, so the block keeps its original title.
  dash_recreate "Recreate"
  say ""
  dash_footnote
  dash_pointer
  return 0
}

